// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1b0ODhAoFPxV-YCKXPSuYE-Y8rjNF4Gs',
    appId: '1:638880468237:web:a2c75be42e206bf824f444',
    messagingSenderId: '638880468237',
    projectId: 'edumind-b89d0',
    authDomain: 'edumind-b89d0.firebaseapp.com',
    storageBucket: 'edumind-b89d0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZCHO-V-Mrhq636qrp289-UP0f4rp-J4w',
    appId: '1:638880468237:android:5170d7e39e5292e024f444',
    messagingSenderId: '638880468237',
    projectId: 'edumind-b89d0',
    storageBucket: 'edumind-b89d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPQkPI0NGIeef7hinNA5aa8XxZgeAZk3c',
    appId: '1:638880468237:ios:856aaf83b1e809f124f444',
    messagingSenderId: '638880468237',
    projectId: 'edumind-b89d0',
    storageBucket: 'edumind-b89d0.firebasestorage.app',
    iosBundleId: 'com.example.aiStudyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPQkPI0NGIeef7hinNA5aa8XxZgeAZk3c',
    appId: '1:638880468237:ios:856aaf83b1e809f124f444',
    messagingSenderId: '638880468237',
    projectId: 'edumind-b89d0',
    storageBucket: 'edumind-b89d0.firebasestorage.app',
    iosBundleId: 'com.example.aiStudyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1b0ODhAoFPxV-YCKXPSuYE-Y8rjNF4Gs',
    appId: '1:638880468237:web:3a8fc757d4d4650d24f444',
    messagingSenderId: '638880468237',
    projectId: 'edumind-b89d0',
    authDomain: 'edumind-b89d0.firebaseapp.com',
    storageBucket: 'edumind-b89d0.firebasestorage.app',
  );
}
