import 'package:flutter/widgets.dart';

class CustomLocalizations {
  final Locale locale;

  CustomLocalizations(this.locale);

  static CustomLocalizations of(BuildContext context) {
    return CustomLocalizations(Localizations.localeOf(context));
  }

  String get(String key) {
    final languageCode = locale.languageCode;
    return _localizedValues[languageCode]?[key] ??
        _localizedValues['en']![key] ??
        key;
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'studyStreak': 'Study Streak',
      'keepItUp': 'Keep it up!',
      'quiz': 'Quiz',
      'googleSuccess': 'Google sign-in successful!',
      'verificationEmailSent': 'Verification email sent! Check your inbox.',
      'typeAMessage': 'Type a message...',
      'clickToUploadPdf': 'Click to upload PDF',
      'orbClick': 'Click',
      'maxFileSize': 'Max file size: 10MB',
      'uploadedSuccessfully': 'Uploaded successfully',
      'uploadNew': 'Upload New',
      'uploadingFile': 'Uploading file...',
      'generatingSummary': 'Generating summary...',
      'generatingQuiz': 'Generating quiz...',
      'errorOccurred': 'An error occurred',
      'yourScore': 'Your score',
      'pdfFile': 'PDF file',
      'aiSummarizerTitle': 'AI Summarizer',
      'uploadPdfSubtitle': 'Upload your PDF and get instant summaries',
      'summaryTitle': '📄 Summary',
      'generateQuiz': 'Generate Quiz',
      'quizSectionTitle': '🎯 Quiz',
      'submitAnswers': 'Submit Answers',
      'reportAProblem': 'Report a Problem',
      'helpSupport': 'Help & Support',
      'wereHereToHelp': "We're here to help you",
      'frequentlyAskedQuestions': 'Frequently Asked Questions',
      'quickHelp': 'Quick Help',
      'quickHelpDescription':
          'Use the chat to ask questions, upload files to get summaries, and track your progress',
      'tellUsWhatWentWrong': 'Tell us what went wrong',
      'briefDescriptionOfIssue': 'Brief description of the issue',
      'reportDetailsHint':
          'Please provide detailed information about the problem you\'re experiencing...',
      'notifications': 'Notifications',
      'stayUpdatedWithYourActivity': 'Stay updated with your activity',
      'notificationSettings': 'Notification Settings',
      'pushNotifications': 'Push Notifications',
      'studyReminders': 'Study Reminders',
      'quizAlerts': 'Quiz Alerts',
      'aiSuggestions': 'AI Suggestions',
      'recentNotifications': 'Recent Notifications',
      'markAllAsRead': 'Mark all as read',
      'clearAll': 'Clear all',
      'noNotificationsYet': 'No notifications yet',
      'academicInformation': 'User Information',
      'yourEducationalDetails': 'Your educational details',
      'universityName': 'University Name',
      'enterYourUniversity': 'Enter your university',
      'facultyCollege': 'Faculty / College',
      'enterYourFaculty': 'Enter your faculty',
      'majorFieldOfStudy': 'Major / Field of Study',
      'enterYourMajor': 'Enter your major',
      'academicYear': 'Academic Year',
      'graduate': 'Graduate',
      'gpa': 'GPA',
      'gpaRangeHint': 'GPA (0.0 - 4.0)',
      'academicInformationSaved': 'Academic information saved!',
      'saveInformation': 'Save Information',
      'manageYourPersonalInformation': 'Manage your personal information',
      'changeProfilePhoto': 'Change profile photo',
      'upload': 'Upload',
      'fullName': 'Full Name',
      'username': 'Username',
      'emailAddress': 'Email Address',
      'phoneNumber': 'Phone Number',
      'aboutMe': 'About Me',
      'changePassword': 'Change Password',
      'enterNewPassword': 'Enter new password',
      'confirmPassword': 'Confirm password',
      'saving': 'Saving...',
      'saveChanges': 'Save Changes',
      'cancel': 'Cancel',
      'deleteAccount': 'Delete Account',
      'profileUpdatedSuccessfully': 'Profile updated successfully',
      'appInfo': 'App Info',
      'aboutEduMind': 'About EduMind',
      'keyFeatures': 'Key Features',
      'aiPoweredChatAssistant': 'AI-powered chat assistant',
      'smartPdfSummarization': 'Smart PDF summarization',
      'quizGeneration': 'Quiz generation',
      'progressTracking': 'Progress tracking',
      'developers': 'Developers',
      'developedByZenithDevsTeam': 'Developed by Zenith Devs Team',
      'privacyPolicy': 'Privacy Policy',
      'termsOfService': 'Terms of Service',
      'howWeProtectYourData': 'How we protect your data',
      'dataWeCollect': 'Data We Collect',
      'howWeUseData': 'How We Use Data',
      'dataSharing': 'Data Sharing',
      'security': 'Security',
      'yourRights': 'Your Rights',
      'introduction': 'Introduction',
      'useOfApp': 'Use of App',
      'userContent': 'User Content',
      'aiDisclaimer': 'AI Disclaimer',
      'account': 'Account',
      'termination': 'Termination',
      'termsAgree': 'By using the app, you agree to these terms',
      'forPersonalUseOnly': 'For personal use only',
      'youAreResponsible': 'You are responsible for what you upload',
      'resultsMayNotBeAccurate': 'Results may not be 100% accurate',
      'youMustKeepYourAccountSecure': 'You must keep your account secure',
      'accountsMayBeSuspended': 'We can suspend accounts if misused',
      'rateYourExperience': 'Rate your experience',
      'submitRating': 'Submit Rating',
      'clickToUploadPdfCard': 'Click to upload PDF',
      'maxFileSizeLabel': 'Max file size: 10MB',
      'addCustomTask': 'Add custom task',
      'newQuizAvailable': 'New Quiz Available',
      'newQuizDescription':
          'Complete \'Advanced Algorithms Quiz\' to earn 50 XP and unlock the next chapter.',
      'twoHoursAgo': '2 hours ago',
      'fiveHoursAgo': '5 hours ago',
      'eightHoursAgo': '8 hours ago',
      'oneDayAgo': '1 day ago',
      'twoDaysAgo': '2 days ago',
      'threeDaysAgo': '3 days ago',
      'aiStudySuggestion': 'AI Study Suggestion',
      'aiStudyDescription':
          'Based on your progress, we recommend reviewing Data Structures for better retention.',
      'studyReminder': 'Study Reminder',
      'studyReminderDescription':
          'Time for your daily 30-minute learning session. Keep your streak alive!',
      'goalAchievement': 'Goal Achievement',
      'goalAchievementDescription':
          'Congratulations! You\'ve completed 70% of your monthly learning goal.',
      'newCourseAvailable': 'New Course Available',
      'newCourseDescription':
          'Machine Learning Fundamentals is now available. Start learning today!',
      'streakMilestone': 'Streak Milestone',
      'streakMilestoneDescription':
          'Amazing! You\'ve maintained a 7-day learning streak. Keep it up!',
      'studySmarterTitle': 'Study Smarter, Not Harder',
      'turnPdfsTitle': 'Turn PDFs into Quizzes Instantly',
      'trackProgressTitle': 'Track Your Progress with AI',
      'gpaLabel': 'GPA',
      'quizzesLabel': 'Quizzes',
      'delete': 'Delete',
      'faq1_q': 'How do I upload study materials?',
      'faq1_a':
          'Tap the upload button on the home screen, select your files (PDF, images, or documents), and our AI will automatically process and summarize them for you.',
      'faq2_q': 'How does AI summarization work?',
      'faq2_a':
          'Our advanced AI analyzes your study materials, extracts key concepts, and creates concise summaries that help you learn faster and retain information better.',
      'faq3_q': 'How can I track my progress?',
      'faq3_a':
          'Visit the Progress tab to view detailed analytics, study streaks, completed materials, and personalized insights about your learning journey.',
      'faq4_q': 'How do I reset my password?',
      'faq4_a':
          'Go to Settings > Security, tap "Change Password", and follow the instructions. You\'ll receive a verification code via email.',
    },
    'ar': {
      'studyStreak': 'سلسلة الدراسة',
      'keepItUp': 'واصل هكذا!',
      'quiz': 'اختبار',
      'googleSuccess': 'تم تسجيل الدخول عبر Google بنجاح!',
      'verificationEmailSent': 'تم إرسال بريد التحقق! تحقق من صندوق الوارد.',
      'typeAMessage': 'اكتب رسالة...',
      'clickToUploadPdf': 'انقر لتحميل ملف PDF',
      'maxFileSize': 'أقصى حجم ملف: 10 ميغابايت',
      'uploadedSuccessfully': 'تم التحميل بنجاح',
      'uploadNew': 'رفع جديد',
      'uploadingFile': 'جارٍ رفع الملف...',
      'generatingSummary': 'جارٍ إنشاء الملخص...',
      'generatingQuiz': 'جارٍ إنشاء الاختبار...',
      'errorOccurred': 'حدث خطأ',
      'yourScore': 'نتيجتك',
      'pdfFile': 'ملف PDF',
      'aiSummarizerTitle': 'مُلخِّص PDF',
      'uploadPdfSubtitle': 'قم بتحميل ملف PDF واحصل على ملخصات فورية',
      'summaryTitle': '📄 الملخص',
      'generateQuiz': 'إنشاء اختبار',
      'quizSectionTitle': '🎯 الاختبار',
      'submitAnswers': 'تسليم الإجابات',
      'reportAProblem': 'الإبلاغ عن مشكلة',
      'helpSupport': 'المساعدة والدعم',
      'wereHereToHelp': 'نحن هنا لمساعدتك',
      'frequentlyAskedQuestions': 'الأسئلة المتكررة',
      'quickHelp': 'مساعدة سريعة',
      'quickHelpDescription':
          'استخدم الدردشة لطرح أسئلة، وتحميل الملفات للحصول على ملخصات، وتتبع تقدمك',
      'tellUsWhatWentWrong': 'أخبرنا بما حدث',
      'briefDescriptionOfIssue': 'وصف موجز للمشكلة',
      'reportDetailsHint':
          'الرجاء تقديم معلومات تفصيلية حول المشكلة التي تواجهها...',
      'notifications': 'الإشعارات',
      'stayUpdatedWithYourActivity': 'تابع نشاطك',
      'notificationSettings': 'إعدادات الإشعارات',
      'pushNotifications': 'إشعارات الدفع',
      'studyReminders': 'تذكيرات الدراسة',
      'quizAlerts': 'تنبيهات الاختبار',
      'aiSuggestions': 'اقتراحات الذكاء الاصطناعي',
      'recentNotifications': 'الإشعارات الأخيرة',
      'markAllAsRead': 'وضع علامة مقروءة للجميع',
      'clearAll': 'مسح الكل',
      'noNotificationsYet': 'لا توجد إشعارات بعد',
      'academicInformation': 'معلومات المستخدم',
      'yourEducationalDetails': 'تفاصيل تعليمك',
      'universityName': 'اسم الجامعة',
      'enterYourUniversity': 'أدخل اسم الجامعة',
      'facultyCollege': 'الكلية',
      'enterYourFaculty': 'أدخل الكلية',
      'majorFieldOfStudy': 'التخصص',
      'enterYourMajor': 'أدخل التخصص',
      'academicYear': 'السنة الأكاديمية',
      'graduate': 'خريج',
      'gpa': 'المعدل',
      'gpaRangeHint': 'المعدل (0.0 - 4.0)',
      'academicInformationSaved': 'تم حفظ المعلومات الأكاديمية!',
      'saveInformation': 'حفظ المعلومات',
      'manageYourPersonalInformation': 'إدارة معلوماتك الشخصية',
      'changeProfilePhoto': 'تغيير صورة الملف الشخصي',
      'upload': 'تحميل',
      'fullName': 'الاسم الكامل',
      'username': 'اسم المستخدم',
      'emailAddress': 'البريد الإلكتروني',
      'phoneNumber': 'رقم الهاتف',
      'aboutMe': 'نبذة عني',
      'changePassword': 'تغيير كلمة المرور',
      'enterNewPassword': 'أدخل كلمة مرور جديدة',
      'confirmPassword': 'تأكيد كلمة المرور',
      'saving': 'جاري الحفظ...',
      'saveChanges': 'حفظ التغييرات',
      'cancel': 'إلغاء',
      'deleteAccount': 'حذف الحساب',
      'profileUpdatedSuccessfully': 'تم تحديث الملف الشخصي بنجاح',
      'appInfo': 'معلومات التطبيق',
      'aboutEduMind': 'حول EduMind',
      'keyFeatures': 'المميزات الرئيسية',
      'aiPoweredChatAssistant': 'مساعد دردشة بالذكاء الاصطناعي',
      'smartPdfSummarization': 'ملخصات ذكية للملفات',
      'quizGeneration': 'توليد الاختبارات',
      'progressTracking': 'تتبع التقدم',
      'developers': 'المطورون',
      'developedByZenithDevsTeam': 'تم التطوير بواسطة فريق Zenith Devs',
      'privacyPolicy': 'سياسة الخصوصية',
      'termsOfService': 'شروط الخدمة',
      'howWeProtectYourData': 'كيف نحمي بياناتك',
      'dataWeCollect': 'البيانات التي نجمعها',
      'howWeUseData': 'كيف نستخدم البيانات',
      'dataSharing': 'مشاركة البيانات',
      'security': 'الأمان',
      'yourRights': 'حقوقك',
      'introduction': 'مقدمة',
      'useOfApp': 'استخدام التطبيق',
      'userContent': 'محتوى المستخدم',
      'aiDisclaimer': 'إخلاء المسؤولية للذكاء الاصطناعي',
      'account': 'الحساب',
      'termination': 'الإنهاء',
      'termsAgree': 'باستخدام التطبيق، أنت توافق على هذه الشروط',
      'forPersonalUseOnly': 'للاستخدام الشخصي فقط',
      'youAreResponsible': 'أنت مسؤول عن ما تقوم بتحميله',
      'resultsMayNotBeAccurate': 'قد لا تكون النتائج دقيقة بنسبة 100٪',
      'youMustKeepYourAccountSecure': 'يجب أن تبقي حسابك آمنًا',
      'accountsMayBeSuspended': 'يمكننا تعليق الحسابات إذا تم إساءة استخدامها',
      'rateYourExperience': 'قيّم تجربتك',
      'submitRating': 'إرسال التقييم',
      'clickToUploadPdfCard': 'انقر لتحميل ملف PDF',
      'orbClick': 'اضغط',
      'maxFileSizeLabel': 'أقصى حجم ملف: 10 ميغابايت',
      'addCustomTask': 'إضافة مهمة مخصصة',
      'newQuizAvailable': 'اختبار جديد متاح',
      'newQuizDescription':
          'أكمل \'اختبار الخوارزميات المتقدمة\' واحصل على 50 نقطة وفتح الفصل التالي.',
      'twoHoursAgo': 'منذ ساعتين',
      'fiveHoursAgo': 'منذ 5 ساعات',
      'eightHoursAgo': 'منذ 8 ساعات',
      'oneDayAgo': 'منذ يوم واحد',
      'twoDaysAgo': 'منذ يومين',
      'threeDaysAgo': 'منذ 3 أيام',
      'aiStudySuggestion': 'اقتراح دراسة ذكي',
      'aiStudyDescription':
          'بناءً على تقدمك، نوصي بمراجعة هياكل البيانات لتحسين الاحتفاظ.',
      'studyReminder': 'تذكير الدراسة',
      'studyReminderDescription':
          'حان الوقت لجلسة التعلم اليومية لمدة 30 دقيقة. احافظ على سلسلتك!',
      'goalAchievement': 'تحقيق الهدف',
      'goalAchievementDescription':
          'تهانينا! لقد أكملت 70% من هدفك التعليمي الشهري.',
      'newCourseAvailable': 'دورة جديدة متاحة',
      'newCourseDescription':
          'أساسيات التعلم الآلي متاحة الآن. ابدأ التعلم اليوم!',
      'streakMilestone': 'علامة فارقة في السلسلة',
      'streakMilestoneDescription':
          'رائع! لقد حافظت على سلسلة تعلم لمدة 7 أيام. استمر!',
      'studySmarterTitle': 'ادرس بذكاء، لا بجهد',
      'turnPdfsTitle': 'حول ملفات PDF إلى اختبارات فوراً',
      'trackProgressTitle': 'تتبع تقدمك بالذكاء الاصطناعي',
      'gpaLabel': 'المعدل',
      'quizzesLabel': 'الاختبارات',
      'delete': 'حذف',
      'faq1_q': 'كيف أقوم بتحميل مواد الدراسة؟',
      'faq1_a':
          'اضغط على زر التحميل في الشاشة الرئيسية، اختر ملفاتك (PDF، صور، أو وثائق)، وسيقوم الذكاء الاصطناعي لدينا بمعالجتها تلقائياً وتلخيصها لك.',
      'faq2_q': 'كيف يعمل تلخيص الذكاء الاصطناعي؟',
      'faq2_a':
          'يحلل الذكاء الاصطناعي المتقدم لدينا مواد الدراسة، يستخرج المفاهيم الرئيسية، ويُنشئ ملخصات موجزة تساعدك على التعلم بشكل أسرع والاحتفاظ بالمعلومات بشكل أفضل.',
      'faq3_q': 'كيف يمكنني تتبع تقدمي؟',
      'faq3_a':
          'زور علامة التبويب التقدم لعرض التحليلات التفصيلية، سلاسل الدراسة، المواد المكتملة، والرؤى الشخصية حول رحلتك التعليمية.',
      'faq4_q': 'كيف أعيد تعيين كلمة المرور؟',
      'faq4_a':
          'اذهب إلى الإعدادات > الأمان، اضغط على "تغيير كلمة المرور"، واتبع التعليمات. ستتلقى رمز التحقق عبر البريد الإلكتروني.',
    },
  };
}
